[package]
name = "google-adsense"
version = "0.2.4"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[[bin]]
name = "adsense-024"
path = "src/main.rs"

[lib]
name = "google_adsense_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2.12", features = ["json"] }

